### ISSUE TITLE
What is the license of the code in this repository?

### ISSUE THREAD

**Issue by kodfodrasz** [joeduffy/aws-tags-example#8]
What is the license in this repository? 

Can I use it, or parts of it, in a commercial project? It was linked by the offical Pulumi blog (https://www.pulumi.com/blog/automatically-enforcing-aws-resource-tagging-policies/), yet I'm uncertain.

**Comment by harryttd** [comment]
I had the same question! Just discovered that great article

**Comment by joeduffy** [comment]
Hi there, sorry for the ambiguity here, I've added an Apache-2.0 license here: https://github.com/joeduffy/aws-tags-example/blob/master/LICENSE. I'd love for folks to use this if you find it helpful!
